### ISSUE TITLE
USB ISP Version 2.0 (MX-USBISP-V3.02) MEGA88 [OK]

### ISSUE THREAD

**Issue by Palingenesis** [aleh/usbisp#10]
Just to inform people I was able to upload main.hex to my USB ISP Version 2.0
PCB version MX-USBISP-V3.02
With a MEGA88 TQFP
I added the 10k Pull-Up Resistor.
All works fine.
If you would like to put the images somewhere?
On a side note. You may want to remove the pin numbers from the schematic PDF. The labels are the important thing, there are several packages so the pin numbers change. for example the pin numbers don't match my chip TQFP.
![USB ISP Version 2 0 001](https://github.com/aleh/usbisp/assets/7996002/0cc9dcdd-42c0-44fe-9813-8ac46e355f73)
![USB ISP Version 2 0 002](https://github.com/aleh/usbisp/assets/7996002/42468354-fc7c-4c80-a128-883a8c5b67e9)
![USB ISP Version 2 0 003](https://github.com/aleh/usbisp/assets/7996002/db5e440a-c3c7-49ed-af41-a88d07150649)
![USB ISP Version 2 0 004](https://github.com/aleh/usbisp/assets/7996002/597ea14c-e1c8-4cd4-86bb-70e11db1ddde)

**Comment by aleh** [comment]
@Palingenesis Hey Tim, thanks for your tip! I've added it to the README.md.

**Comment by Palingenesis** [comment]
Cool, thank you.
