### ISSUE TITLE
avrdude: error:target doesn't answer 

### ISSUE THREAD

**Issue by kamrulroky** [aleh/usbisp#5]
Thanks a lot for providing a legit solution , I have bought two other different programmer after this one didn't work. Your solution sort of worked for me but with a problem.

I have uploaded the hex file to the programmer.my windows pc recognizes it as USBasp and also the blue led workes too. But if i try to program a chip it shows the error 
`avrdude: error: program enable: target doesn't answer. 1 
avrdude: initialization failed, rc=-1`
Which you mentioned too if anything is not connected. But I have connected everything properly and I am sure because with other USBasp the wiring works. What might be the problem here ,any suggestions?

**Comment by kamrulroky** [comment]
ok ,I figured that out.Although its quite a regular issue  but I have not noticed it. the problem is with internal clock speed of the chip.if its set default to 1MHz which is lower than USBasp and  programmer can't slow down for this. Using -B 3 parameter on avrdude solved my problem . Thank you again

**Comment by aleh** [comment]
Ah, glad you solved it! 

I have similar issue when working with new ATtiny85's: have to use -B when disabling the DIV8 fuse.
