### ISSUE TITLE
MX-USBISP-V6.00

### ISSUE THREAD

**Issue by steadramon** [aleh/usbisp#8]
![image](https://user-images.githubusercontent.com/866195/89214223-584a7a80-d5be-11ea-8686-e5a8cd0b8f53.png)
![image](https://user-images.githubusercontent.com/866195/89213811-97c49700-d5bd-11ea-93c3-d9a6ee393624.png)
![image](https://user-images.githubusercontent.com/866195/89213839-a317c280-d5bd-11ea-8f91-6d05a65bb5ff.png)

Had one of these v6.00 boards come through with some stuff, didn't need another so put it up for sacrifice

Had to flash using "-p ATmega88P" but is working fine otherwise

Thanks!

**Comment by aleh** [comment]
Many thanks for the info! Incorporated it into the readme.

**Comment by drencorxeen** [comment]
You have a link to where this version can be bought?

**Comment by aleh** [comment]
@steadramon ^

**Comment by aleh** [comment]
@drencorxeen May I ask why do you need exactly version 6 of the board? They appear to work the same as USBisp and they all have 2.0 label on the box itself.

**Comment by steadramon** [comment]
It actually came with a BLTouch sensor for my 3D printer - it came as part of the official package from Creality for upgrading the Ender 3 - this came from the Creality official store on Aliexpress

**Comment by o-dka** [comment]
I actually flashed it via m88 not m88p , and it worked too!

**Comment by aleh** [comment]
@o-dka Cool! Thanks for letting us know!

**Comment by o-dka** [comment]
> I actually flashed it via m88 not m88p , and it worked too!

I was wrong, it worked once and then I needed to reflash it XD

**Comment by rklasen** [comment]
> I actually flashed it via m88 not m88p , and it worked too!

Same here, although I had the V5.00, also from a Creality BLtouch Kit. Thanks for this repo!
