### ISSUE TITLE
Windows 10 driver

### ISSUE THREAD

**Issue by crewshin** [aleh/usbisp#9]
Sorry for the misuse of _issues_ here, however I've looked all over the internet for a driver that works for these. Do you have any idea where I can find one? I see you have a couple in the bin folder but those don't seem to work. It just says that I currently have a better one installed.

Feel free to close if you don't want to deal with this :)

**Comment by aleh** [comment]
@crewshin Hey! It's not a problem to use issues however I don't know what's the state of things on Windows. Have you tried to use it with avrdude without a driver?

**Comment by dl6lr** [comment]
Normally using Zadig to install the libusb driver works just fine (using admin access). avrdude does not access the USB device without a libusb driver despite the device being attached:

c:\compiler\avrdude>avrdude -v -cusbasp -pm88

avrdude: Version 6.3, compiled on Feb 17 2016 at 09:25:53
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "c:\compiler\avrdude\avrdude.conf"

         Using Port                    : usb
         Using Programmer              : usbasp
avrdude: error: could not find USB device with vid=0x16c0 pid=0x5dc vendor='www.fischl.de' product='USBasp'

avrdude done.  Thank you.

c:\compiler\avrdude>wmic path CIM_LogicalDevice where "Description like 'USBasp'" get /value

Availability=
Caption=USBasp
ClassGuid=
CompatibleID={"USB\Class_00&amp;SubClass_00&amp;Prot_00","USB\Class_00&amp;SubClass_00","USB\Class_00"}
ConfigManagerErrorCode=28
ConfigManagerUserConfig=FALSE
CreationClassName=Win32_PnPEntity
Description=USBasp
DeviceID=USB\VID_16C0&amp;PID_05DC\7&amp;6F3892C&amp;0&amp;1
ErrorCleared=
ErrorDescription=
HardwareID={"USB\VID_16C0&amp;PID_05DC&amp;REV_0106","USB\VID_16C0&amp;PID_05DC"}
InstallDate=
LastErrorCode=
Manufacturer=
Name=USBasp
PNPClass=
PNPDeviceID=USB\VID_16C0&amp;PID_05DC\7&amp;6F3892C&amp;0&amp;1
PowerManagementCapabilities=
PowerManagementSupported=
Present=TRUE
Service=
Status=Error
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=EW6651NB

**Comment by crewshin** [comment]
Thanks for the info guys! I wasn't able to get this to work at all, however I found a somewhat silly workaround. I just installed a fresh copy of widows as a VM and did the flash through that.

Thanks again

**Comment by aleh** [comment]
Thanks @dl6lr!

**Comment by dl6lr** [comment]
For those who do not find it, Zadig is located here: https://zadig.akeo.ie/
It is not perfect but it works way easier than handling with .sys and .inf files for yourself. However I have one situation where it fails to install the driver, despite being (one) Admin.
